FROM node:20.15-bullseye-slim AS base

ENV PNPM_HOME="/pnpm" \
    PATH="$PNPM_HOME:$PATH"
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get autoclean && \
    apt-get install -y curl && \
    apt-get install -y g++ make python3 && \
    npm install -g corepack@latest && \
    corepack enable

FROM base AS dev
WORKDIR /app

CMD pnpm install --config.confirmModulesPurge=false; pnpm dev

FROM base AS deps
WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN make setup_npm_registry && \
    pnpm install --frozen-lockfile

FROM base AS builder
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN pnpm run build

FROM base AS ci

WORKDIR /app

COPY --from=builder /app/.next/standalone ./.next/standalone
COPY --from=builder /app/.next/static ./.next/standalone/.next/static
COPY --from=deps /app/node_modules ./node_modules
COPY . .

CMD node ./.next/standalone/server.js

FROM base AS runner

RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

WORKDIR /app/temp

COPY --from=builder /app/.next/static ./_assets/static

COPY --from=builder /app/nextjs ./nextjs
COPY --from=builder /app/node_modules ./node_modules

WORKDIR /app

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/docker/nextjs/entrypoint.sh ./

USER nextjs

ENV NEXT_TELEMETRY_DISABLED=1
